"""Regenerate patches 0003 (socktap build + main.cpp) and 0004 (socktap docs) from pristine Vanetza files."""
import os
import subprocess
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SUB = os.path.join(ROOT, "external", "vanetza")


def upstream(path):
    out = subprocess.run(["git", "-c", "core.autocrlf=false", "-C", SUB, "show", "HEAD:" + path],
                         check=True, capture_output=True)
    return out.stdout.decode("utf-8")


def edit(text, pairs):
    for old, new in pairs:
        # explicit check, assert would vanish with python -O
        if text.count(old) != 1:
            raise RuntimeError("upstream context changed: " + old)
        text = text.replace(old, new)
    return text


def diff(path, before, after):
    with tempfile.TemporaryDirectory() as tmp:
        a = os.path.join(tmp, "a", path)
        b = os.path.join(tmp, "b", path)
        for name, content in ((a, before), (b, after)):
            os.makedirs(os.path.dirname(name), exist_ok=True)
            with open(name, "w", encoding="utf-8", newline="\n") as f:
                f.write(content)
        out = subprocess.run(["git", "-c", "core.autocrlf=false", "diff", "--no-index",
                              "a/" + path, "b/" + path], cwd=tmp, capture_output=True)
        return out.stdout.decode("utf-8").replace("a/a/", "a/").replace("b/b/", "b/")


NL = "\n"

cmake = "tools/socktap/CMakeLists.txt"
cmake_new = edit(upstream(cmake), [
    ("    ethernet_device.cpp" + NL, "    ethernet_device.cpp" + NL + "    fixed_time_intersection.cpp" + NL),
    ("    positioning.cpp" + NL, "    positioning.cpp" + NL + "    priority_request_table.cpp" + NL),
    ("    raw_socket_link.cpp" + NL, "    raw_socket_link.cpp" + NL + "    rlt_application.cpp" + NL),
    ("    target_sources(socktap PRIVATE gps_position_provider.cpp)" + NL + "endif()" + NL,
     "    target_sources(socktap PRIVATE gps_position_provider.cpp)" + NL + "endif()" + NL + NL
     + "add_test_subdirectory(tests)" + NL),
    ("    time_trigger.cpp" + NL, "    time_trigger.cpp" + NL + "    tlc_request_application.cpp" + NL
     + "    tlc_status_application.cpp" + NL + "    tlm_application.cpp" + NL),
])

main = "tools/socktap/main.cpp"
options = [
    '        ("intersection-id", po::value<unsigned>()->default_value(1), "Intersection ID used in generated SPATEMs, MAPEMs and SREMs.")',
    '        ("spatem-interval", po::value<unsigned>()->default_value(100), "SPATEM sending interval in milliseconds, 0 receives only.")',
    '        ("mapem-interval", po::value<unsigned>()->default_value(1000), "MAPEM sending interval in milliseconds, 0 receives only.")',
    '        ("srem-interval", po::value<unsigned>()->default_value(1000), "SREM sending interval in milliseconds, 0 receives only.")',
    '        ("print-rx", "Print messages received by tlm, rlt, tlc-request and tlc-status")',
    '        ("print-tx", "Print messages generated by tlm, rlt, tlc-request and tlc-status")',
]
apps = """            } else if (app_name == "tlm") {
                std::unique_ptr<TlmApplication> tlm {
                    new TlmApplication(trigger.runtime(), example_intersection())
                };
                tlm->set_interval(std::chrono::milliseconds(vm["spatem-interval"].as<unsigned>()));
                tlm->set_station_id(vm["station-id"].as<unsigned>());
                tlm->print_received_message(vm.count("print-rx") > 0);
                tlm->print_generated_message(vm.count("print-tx") > 0);
                apps.emplace(app_name, std::move(tlm));
            } else if (app_name == "rlt") {
                std::unique_ptr<RltApplication> rlt {
                    new RltApplication(*positioning, trigger.runtime(), example_intersection())
                };
                rlt->set_interval(std::chrono::milliseconds(vm["mapem-interval"].as<unsigned>()));
                rlt->set_station_id(vm["station-id"].as<unsigned>());
                rlt->print_received_message(vm.count("print-rx") > 0);
                rlt->print_generated_message(vm.count("print-tx") > 0);
                apps.emplace(app_name, std::move(rlt));
            } else if (app_name == "tlc-request") {
                std::unique_ptr<TlcRequestApplication> request {
                    new TlcRequestApplication(trigger.runtime(), vm["intersection-id"].as<unsigned>())
                };
                request->set_interval(std::chrono::milliseconds(vm["srem-interval"].as<unsigned>()));
                request->set_station_id(vm["station-id"].as<unsigned>());
                request->print_received_message(vm.count("print-rx") > 0);
                request->print_generated_message(vm.count("print-tx") > 0);
                apps.emplace(app_name, std::move(request));
            } else if (app_name == "tlc-status") {
                std::unique_ptr<TlcStatusApplication> status {
                    new TlcStatusApplication(example_intersection(), trigger.runtime())
                };
                status->set_station_id(vm["station-id"].as<unsigned>());
                status->print_received_message(vm.count("print-rx") > 0);
                status->print_generated_message(vm.count("print-tx") > 0);
                apps.emplace(app_name, std::move(status));
            } else {
"""
main_new = edit(upstream(main), [
    ('#include "positioning.hpp"' + NL, '#include "positioning.hpp"' + NL + '#include "rlt_application.hpp"' + NL),
    ('#include "time_trigger.hpp"' + NL, '#include "time_trigger.hpp"' + NL + '#include "tlc_request_application.hpp"' + NL
     + '#include "tlc_status_application.hpp"' + NL + '#include "tlm_application.hpp"' + NL),
    ('"Run applications [ca,hello,benchmark]")' + NL,
     '"Run applications [ca,hello,benchmark,tlm,rlt,tlc-request,tlc-status]")' + NL + NL.join(options) + NL),
    ("        std::map<std::string, std::unique_ptr<Application>> apps;" + NL,
     "        // example intersection of the tlm, rlt and tlc-status applications, built on first use" + NL
     + "        std::unique_ptr<FixedTimeIntersection> intersection;" + NL
     + "        auto example_intersection = [&]() -> const FixedTimeIntersection& {" + NL
     + "            if (!intersection) {" + NL
     + "                intersection.reset(new FixedTimeIntersection(vm[\"intersection-id\"].as<unsigned>()));" + NL
     + "            }" + NL
     + "            return *intersection;" + NL
     + "        };" + NL
     + "        std::map<std::string, std::unique_ptr<Application>> apps;" + NL),
    ("                apps.emplace(app_name, std::move(benchmark));" + NL + "            } else {" + NL,
     "                apps.emplace(app_name, std::move(benchmark));" + NL + apps),
])

app_hpp = "tools/socktap/application.hpp"
app_hpp_new = edit(upstream(app_hpp), [(
    "    DataConfirm request(const DataRequest&, DownPacketPtr);" + NL,
    "    DataConfirm request(const DataRequest&, DownPacketPtr);" + NL
    + "    DataConfirm request(const DataRequest&, DownPacketPtr, PortType destination);" + NL)])

app_cpp = "tools/socktap/application.cpp"
app_cpp_new = edit(upstream(app_cpp), [
    ("Application::DataConfirm Application::request(const DataRequest& request, DownPacketPtr packet)" + NL + "{" + NL,
     "Application::DataConfirm Application::request(const DataRequest& request, DownPacketPtr packet)" + NL + "{" + NL
     + "    return this->request(request, std::move(packet), this->port());" + NL + "}" + NL + NL
     + "Application::DataConfirm Application::request(const DataRequest& request, DownPacketPtr packet, PortType destination)" + NL
     + "{" + NL),
    ("        btp_header.destination_port = this->port();" + NL,
     "        btp_header.destination_port = destination;" + NL),
])

docs = "docs/tools/socktap.md"
docs_new = edit(upstream(docs), [(
    """You can choose from three simple example V2X applications to run with *socktap* via the `--applications` argument:

- *ca* sends Cooperative Awareness Messages (CAM)
- *hello* sends simple BTP-B message with the binary payload `0xc0ffee`
- *benchmark* counts the number of any received messages and prints the current message rate once per second
""",
    """You can choose from seven simple example V2X applications to run with *socktap* via the `--applications` argument:

- *ca* sends Cooperative Awareness Messages (CAM)
- *hello* sends simple BTP-B message with the binary payload `0xc0ffee`
- *benchmark* counts the number of any received messages and prints the current message rate once per second
- *tlm* sends Signal Phase and Timing Extended Messages (SPATEM) of an example intersection
- *rlt* sends MAP Extended Messages (MAPEM) describing the lanes of this intersection at the station's position
- *tlc-request* sends Signal Request Extended Messages (SREM) of a tram asking for priority and prints the answers
- *tlc-status* answers SREM for the example intersection by Signal Request Status Extended Messages (SSEM)

The example intersection joins a main road with tram tracks and a side road: nine signal groups for vehicles, pedestrians and trams, two stages and five coordinated fixed-time plans selected by a weekly schedule (see `vanetza/facilities/fixed_time_plan.hpp`).
Protected or permissive movement states are derived from conflicting paths of signal groups served in the same stage.
The example controller has no priority logic, so *tlc-status* answers valid requests with status *processing*.
For example, run a road-side and a vehicle station on one host:

    :::shell
    socktap -l udp -a tlm rlt tlc-status --positioning static --latitude 49.0 --longitude 11.4 --intersection-id 7
    socktap -l udp -a tlm rlt tlc-request --spatem-interval 0 --mapem-interval 0 --intersection-id 7 --mac-address 02:00:00:00:00:02 --print-rx

See [Generating SPATEM and MAPEM](../recipes/spatem-mapem.md) for the underlying helper functions.
""")])

with open(os.path.join(ROOT, "patches", "0003-tools-socktap-tlm-rlt-applications.patch"), "w", encoding="utf-8", newline="\n") as f:
    f.write(diff(cmake, upstream(cmake), cmake_new) + diff(main, upstream(main), main_new)
            + diff(app_hpp, upstream(app_hpp), app_hpp_new) + diff(app_cpp, upstream(app_cpp), app_cpp_new))
with open(os.path.join(ROOT, "patches", "0004-docs-socktap-tlm-rlt.patch"), "w", encoding="utf-8", newline="\n") as f:
    f.write(diff(docs, upstream(docs), docs_new))
print("patches written")
